from tkinter import *
from tkinter import ttk

root = Tk()
root.title("Comunication Control")
root.minsize(400,200)
frm = ttk.Frame(root, padding=20)
frm.grid(column=0,row=0, columnspan=3,rowspan=5)
broadcast_d1_mute = IntVar()
broadcast_d2_mute = IntVar()
broadcast_d3_mute = IntVar()
broadcast_d1_defean = IntVar()
broadcast_d2_defean = IntVar()
broadcast_d3_defean = IntVar()
ttk.Label(frm, text="Broadcast Channel").grid(column=0, row=0, columnspan=3)
ttk.Label(frm, text="Mute").grid(column=1, row=1)
ttk.Label(frm, text="Defean").grid(column=2, row=1)
ttk.Label(frm, text="Device 1").grid(column=0, row=2)
ttk.Checkbutton(frm, variable=broadcast_d1_mute).grid(column=1, row=2)
ttk.Checkbutton(frm, variable=broadcast_d1_defean).grid(column=2, row=2)
ttk.Label(frm, text="Device 2").grid(column=0, row=3)
ttk.Checkbutton(frm, variable=broadcast_d2_mute).grid(column=1, row=3)
ttk.Checkbutton(frm, variable=broadcast_d2_defean).grid(column=2, row=3)
ttk.Label(frm, text="Device 3").grid(column=0, row=4)
ttk.Checkbutton(frm, variable=broadcast_d3_mute).grid(column=1, row=4)
ttk.Checkbutton(frm, variable=broadcast_d3_defean).grid(column=2, row=4)
frm2 = ttk.Frame(root, padding=20)
frm2.grid(column=3,row=0, columnspan=2, rowspan=4)
private_d1_mute = IntVar()
private_d2_mute = IntVar()
ttk.Label(frm2, text="Private Channel 1").grid(column=6,row=0, columnspan=2)
ttk.Label(frm2, text="Mute").grid(column=7, row=1)
ttk.Label(frm2, text="Device 1").grid(column=6, row=2)
ttk.Checkbutton(frm2, variable=private_d1_mute).grid(column=7, row=2)
ttk.Label(frm2, text="Device 2").grid(column=6, row=3)
ttk.Checkbutton(frm2, variable=private_d2_mute).grid(column=7, row=3)
frm3 = ttk.Frame(root, padding=10)
frm3.grid(column=6,row=5, columnspan=2)
ttk.Button(frm3, text="Quit", command=root.destroy).grid(column=6, row=5, columnspan=2)
root.mainloop()
